### ISSUE TITLE
Create a table for the number of operators and their accompanying fault tolerance

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/obol-docs#114]
## Problem to be solved

We don't have a good graphical explainer to my knowledge of explaining why 4, 7, and 10 node clusters are 'good'. And the off numbers are less so. 

## Proposed solution

Make a 3 column table from 4 to 10 nodes, indicating their fault tolerance and a note column to describe them a little. 

When we get a designer we can do graphics like the 3/4 lock image but for more quantities, to make it even more explicit how the validator works. 

<img width="600" alt="ThresholdSigning" src="https://user-images.githubusercontent.com/4981644/216774759-7843973c-d07d-4644-913d-ae5a215f9fb8.png">

**Comment by thomasheremans** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/19) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by EridianAlpha** [comment]
@OisinKyne I've made a simple table for this. My two outstanding questions are:

1. Where should it be placed? I've initially placed it at the bottom of this heading: https://docs.obol.tech/docs/int/key-concepts#distributed-validator-key
2. What should the notes be? Is there reference information available explaining what is good/bad?

<img width="407" alt="image" src="https://user-images.githubusercontent.com/86061486/220654267-de7b18ed-c1ed-4136-9839-7474f67e7d9a.png">
