### ISSUE TITLE
Create a guide for `charon combine`

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/obol-docs#123]
# 🎯 Problem to be solved

We have a new command, one that combines key shares into classic single private keys. We need to make a guide to explain how to use it and to maximally warn people not to slash themselves doing this.

- [x] Link to the codebase issue that prompted this docs change https://github.com/ObolNetwork/charon/issues/1311 

# 🛠️ Proposed solution

Make a guide for combining key shares back into a single set of private keys. Add many caveats and `:::warn` admonitions about getting slashed to the guide.

- [ ] For major overhaul of docs, design doc link: 

# 🧪 Tests

- [ ] Netlify deployment build tests passing

# 👐 Additional acceptance criteria

# ❌ Out of Scope

Explaining to people a safe way to transmit key material to one person for a combination.

**Comment by thomasheremans** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/25) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by thomasheremans** [comment]
Also in the CLI reference

**Comment by gsora** [comment]
CLI reference PR has been opened, will work on a guide tomorrow

**Comment by gsora** [comment]
A CLI reference, quickstart guide have been written and are available as a PR here: https://github.com/ObolNetwork/obol-docs/pull/134.
