### ISSUE TITLE
Create a guide for `charon exit`

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/obol-docs#124]
# 🎯 Problem to be solved

We have a new command, one that works in cdvn to exit a set of validator keys which is as follows:
```
> docker exec -ti charon-distributed-validator-node-teku-1 /opt/teku/bin/teku voluntary-exit \
--beacon-node-api-endpoint="http://charon:3600/" \
--confirmation-enabled=false \
--validator-keys="/opt/charon/validator_keys:/opt/charon/validator_keys" \
--epoch=${EXIT_EPOCH:-112260}
```

We need to make a guide to explain how to use it.

- [x] Link to the codebase issue that prompted this docs change https://github.com/ObolNetwork/charon-distributed-validator-node/issues/162

# 🛠️ Proposed solution

Make a guide for broadcasting the exit of a validator. Explain that you need a quorum of operators to do this for the exit to succeed, and that if every charon node restarts it will lose the partial exit and you will have to begin again.  

- [ ] For major overhaul of docs, design doc link: 

# 🧪 Tests

- [ ] Netlify deployment build tests passing

# 👐 Additional acceptance criteria

# ❌ Out of Scope

Explaining to people a safe way to transmit key material to one person for a combination.

**Comment by OisinKyne** [comment]
Blocked because we can't presign exits. Probably will be basically rewritten/reopened

**Comment by EridianAlpha** [comment]
@OisinKyne is it possible to write this now withdrawals are enabled on Goerli?

**Comment by LukeHackett12** [comment]
> @OisinKyne is it possible to write this now withdrawals are enabled on Goerli?

Yep, this is good to go. Have amended the description with the right command 👍🏼
