### ISSUE TITLE
Replace legacy exit guide

### ISSUE THREAD

**Issue by Battenfield** [ObolNetwork/obol-docs#161]
# 🎯 Problem to be solved

Replace the legacy exit guides to link out to the new guide
New: https://docs.obol.tech/docs/next/int/quickstart/quickstart-exit
Old: https://docs.obol.tech/docs/int/quickstart/group/quickstart-group-operator#step-8-validator-voluntary-exit

# 🛠️ Proposed solution

**Comment by Battenfield** [comment]
Is the new guide/command sufficient for every user, or would the legacy exit guide cover some edge cases? @LukeHackett12

**Comment by LukeHackett12** [comment]
> Is the new guide/command sufficient for every user, or would the legacy exit guide cover some edge cases? @LukeHackett12

Yeah we should remove this.
