### ISSUE TITLE
delete `/blog` directory

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/obol-docs#175]
# 🎯 Problem to be solved

The `/blog` folder in the repo it is not updated and it is not used anywhere.

# 🛠️ Proposed solution

Delete the `/blog` directory.

# 🧪 Tests

Remember to test it since there maybe broken links.

Probably, something breaks in `docusaurus.js`, you need to turn a boolean false somewhere and not just delete it.

# ❌ Out of Scope

**Comment by adityakode** [comment]
Hi !
I would love to work on this!
