### ISSUE TITLE
CDVN "run a cluster alone" flow has wrong Docker compose flow

### ISSUE THREAD

**Issue by gsora** [ObolNetwork/obol-docs#187]
## Describe the bug

The "[Run a cluster alone](https://docs.obol.tech/docs/int/quickstart/quickstart-alone)" execution flow doesn't take into account the fact that `charon create cluster` creates one directory for each new node under `.charon/cluster`.

This means that the `docker-compose.yml` file cannot find `.charon/cluster-lock.json` and private key file. 

## Expected behavior
`docker compose` starts a single node off the cluster.

**Comment by OisinKyne** [comment]
Closed as changed and no longer accurate.
