### ISSUE TITLE
Create an SDK reference

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/obol-docs#238]
# 🎯 Problem to be solved

We have a quickstart for the SDK, but no comprehensive reference of its features. This means people need to read the source code of the SDK (which is still private) to see what it does. 

# 🛠️ Proposed solution

Export [typedoc](https://typedoc.org/example/modules.html) from the SDK, and include it in our docusaurus site the same way we have incorporated a swagger spec. 

If unfeasible we can do it manually, but that is plan b and needs a verbal confirmation that we are going that route. 

# 🧪 Tests

- [ ] Netlify deployment build tests passing

# 👐 Additional acceptance criteria
The typedoc artifact is exported from obol-packages CI/CD, and is pulled into the docs repo in an automated fashion, meaning it never gets stale (like the current swagger spec does)

# ❌ Out of Scope

Finishing the quickstart guide

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/obol-docs/238?planning-poker) with Zenhub @f1lander @HananINouman
