### ISSUE TITLE
Link doesn't work as well

### ISSUE THREAD

**Issue by KyryloKilin** [ObolNetwork/obol-docs#240]
## 🎯 Problem to be solved
At https://docs.obol.tech/docs/int/quickstart/advanced/prysm-vc when using/clicking on compose-prysm.yml link (https://github.com/ObolNetwork/charon-distributed-validator-cluster/blob/main/compose-prysm.yml) appears 404 - page not found.

![image](https://github.com/ObolNetwork/obol-docs/assets/83702309/2b092360-409c-4254-a318-b344392c6da3)
![image](https://github.com/ObolNetwork/obol-docs/assets/83702309/a3235351-8a1c-4ed3-b381-bf3430d8730d)

## 🛠️ Proposed solution
Need to change link address

## ❌ Out of Scope

**Comment by xenowits** [comment]
Thanks for reporting this! 

Prysm VC is actually not compatible with charon, so this docs page is no longer valid. This page should be deleted.
