### ISSUE TITLE
Update documentation for running a cluster with MEV-Boost

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/obol-docs#254]
## 🎯 Problem to be solved
The documentation page for running a cluster with MEV-Boost on the Obol Network is outdated and does not reflect the current MEV-boost approach. There is confusion about whether to include details about the alpha feature in the documentation, especially since a related ticket was created earlier, but the page remains inaccurate.

## 🛠️ Proposed solution
- [ ] **Evaluate Current Documentation**: Review the existing page at [Obol Network - Run a cluster with MEV-Boost](https://docs.obol.tech/docs/int/quickstart/advanced/quickstart-builder-api) to determine the specific inaccuracies and outdated information.
- [ ] **Update MEV-Boost Approach**: Implement the necessary changes to represent the current MEV-boost approach, aligning with the existing ticket [#218](https://github.com/ObolNetwork/obol-docs/issues/218).

Context: https://docs.google.com/document/d/1lCYiEv7JmVYymp4CBrEvExj3WNmSqWVvZwl9dwATCmA/edit#heading=h.mssb0822zapb

**Comment by alansunny3** [comment]
Meeting extract:

Alan will work on updating the web documentation, while Dhruv proposes updates for the Readme file. They emphasize the importance of synchronizing their efforts to ensure accurate documentation. Once ready, Alan will add them both to the review list.
