### ISSUE TITLE
Add public relays to docs

### ISSUE THREAD

**Issue by LukeHackett12** [ObolNetwork/obol-docs#268]
# 🎯 Problem to be solved

We have 4 external public relays listed on `https://status.obol.tech`, but they are not listed in the documentation

# 🛠️ Proposed solution

Create a "Public Relays" tab or similar where we list the third party relays that we have for decentralisation.

**Comment by OisinKyne** [comment]
Added an extra pointer to the page on risks, think this is covered enough now.
