### ISSUE TITLE
Fix the API doc

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/obol-docs#292]
## 🎯 Problem to be solved
- The API documentation, probably related to the `Content-Security-Policy` header fixed in  [Missing X-Frame-Options HTTP header#656](https://app.zenhub.com/workspaces/obol-workspace-648c1170ee94656741353327/issues/gh/obolnetwork/dv-launchpad/656) ,  appears to be broken.
- There's a lack of integration between the API docs and the SDK docs, creating confusion and inefficiency.
<img width="1808" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0E0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d852c8eaa0cb593e44f1a3437a2c461f53f7022/image.png" alt="image.png" />

## 🛠️ Proposed solution
- [ ] Implement the changes and test to ensure the combined documentation functions as intended.

**Comment by LukeHackett12** [comment]
closing as dupe of https://github.com/ObolNetwork/obol-api/issues/471
