### ISSUE TITLE
Onboard nodeguardians charon relay

### ISSUE THREAD

**Issue by aly-obol** [ObolNetwork/obol-docs#333]
# 🎯 Problem to be solved
Onboard https://obol-relay.nodeguardians.io/ charon public relay

# 🛠️ Proposed solution
- Add to docs
- Add to pagerduty
- Add to central monitoring

# 🧪 Tests
- [ ] Netlify deployment build tests passing

**Comment by OisinKyne** [comment]
Closed in #334
