### ISSUE TITLE
Review and Add missing query parameters on Obol docs

### ISSUE THREAD

**Issue by anadi2311** [ObolNetwork/obol-docs#366]
### Problem
We found `details` is a missing query parameter from [get cluster locks by network endpoint](https://docs.obol.tech/api#tag/Cluster-Lock/operation/LockController_getClusterLocksByNetwork).  We should make all the query parameters are always present.

### Solution
- Add `details` in  [get cluster locks by network endpoint](https://docs.obol.tech/api#tag/Cluster-Lock/operation/LockController_getClusterLocksByNetwork) on docs. 
- Review all other endpoints to make sure no other query parameters are missing and add them too.
- Set up SOP in endpoint creation checklist so this doesn't happen.

**Comment by LukeHackett12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/obol-docs/366?planning-poker) with Zenhub @redecvi @HananINouman
