### ISSUE TITLE
Sync Quickstart docs with node repo quickstart

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/obol-docs#40]
### Issue to be solved
A lot of changes have been made to the node repo quickstart that are not yet reflected in the [docs](https://docs.obol.tech/docs/int/quickstart/quickstart-group#getting-started-with-charon) (which are still on v0.8).

 In my opinion, they should be a copy paste from each other with the README as source of truth. 

[Optional] Maybe there is a way to keep these sections in sync automatically through an automation?

**Comment by OisinKyne** [comment]
ObolNetwork/obol-docs#26 and ObolNetwork/obol-docs#27 are relating to automating the release of the docs and auto updating one page of the docs automatically based on an upstream trigger in the charon repo. Have been low on the devops to do list for the last while
