### ISSUE TITLE
fix link to `Edit this page`

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/obol-docs#45]
## Problem to be solved

The `Edit this page` button link at the bottom of all pages of [docs](docs.obol.tech) is broken.

<img width="612" alt="Screenshot 2022-08-18 at 4 57 06 PM" src="https://user-images.githubusercontent.com/43061995/185384144-9653f6c0-7eae-46c6-89d7-08e44d084caa.png">

<img width="1416" alt="Screenshot 2022-08-18 at 4 58 04 PM" src="https://user-images.githubusercontent.com/43061995/185384392-f0f8609e-6990-4b9f-8ad9-ad34086d3e2e.png">

## Proposed Solution

Fix link so that the user is redirected to a page on github where he/she can update the details and raise a proper PR.

**Comment by OisinKyne** [comment]
Fixed in #46
